auth0:
  auth0_domain:
    client: true
    default: 'YOUR-AUTH0-ACCOUNT.auth0.com'
  auth0_client_id:
    client: true
    default: ''
  auth0_client_secret:
    default: ''
  auth0_callback_url:
    client: true
    default: 'http://your-discourse-url.com/auth/auth0/callback'
  auth0_connection:
    client: true
    default: ''